### ISSUE TITLE
CordovaPayTM plugin call but not redirect paytm page

### ISSUE THREAD

**Issue by sagar2914** [isathyam/CordovaPayTM#7]
Hi ,

I am trying to implement paytm integration in my hybrid app. I have set the required parameters and yet its not calling the server.

While installing the plugin have given the required variables; checksum generate url , checksum verify url, webiste, mid , industry type id and on button click am calling window.plugins.paytm.startPayment(orderId, custid, 'email', mobile, amount, successCallback, failureCallback) function with proper params.

on calling, but not get any message or any page.

This is for android platform. I have tried putting window.plugin code in device ready function and it is of no help.

How can I set the call for staging server and production server. ?
Can you please help in this.

**Comment by lashak** [comment]
same problem give any suggestion Please ?

**Comment by sufiyaq** [comment]
same issue, any update.

**Comment by ranjitseth123** [comment]
any update on this one. trying to use this plugin with ionic 3 .. always getting 'network not available'

**Comment by sagargheewala** [comment]
@ranjitseth123 I am not use currently this plugin.

I have build own login and use InAppBrowser Plugin to open paytm page.

**Comment by ranjitseth123** [comment]
Oh. thats fine. thank you. but is there a straight forward way to use any
plugin for ionic/cordova .. i am new to mobile apps.

**Comment by sagargheewala** [comment]
@ranjitseth123  Sorry, no idea.

**Comment by shwetagharshi** [comment]
> @ranjitseth123 I am not use currently this plugin.
> 
> I have build own login and use InAppBrowser Plugin to open paytm page.

Hi , Could you please share the code to show how have u used InAppBrowser. I am unable to redirect to patym page using InAppBrowser. Stuck at it from a long time. Any help would be great use.
